name: Keep Streamlit App Alive

on:
  schedule:
    - cron: "*/15 * * * *"  # Her 15 dakikada bir çalıştır
  workflow_dispatch:  # Manuel çalıştırma için buton ekler

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Streamlit app
        run: curl -X GET "https://excel-sheet-splitter-nwfuusmt5cakadaupkfxrl.streamlit.app/"
